# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'navigations' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for navigations
  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 5.15.0'
  target 'navigations-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'navigationsTests' do
    inherit! :search_paths
    # Pods for testing
  end



end
