# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'navigations' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for navigations
  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'navigationsTests' do
    inherit! :search_paths
    # Pods for testing
  end



end
